public class FreshdeskContacts{
	public boolean active;
	public String address;
	public String company_id;
	public boolean deleted;
	public String description;
	public String email;	
	public Integer id;	
	public String job_title;
	public String language;	
	public String mobile;
	public String name;	
	public String phone;
	public String time_zone;	
	public String twitter_id;
	public String created_at;	
	public String updated_at;	
	public String[] other_companies;
	public custom_fields custom_fields;
	
    public class custom_fields {
		public String department;	
		public String fb_profile;	
		public boolean permanent;
	}
}